Add Body to FacadeDocBodyResponse
lamoda/crpt-ismp-api-client pull request #3
Opened 2019-12-12 13:12 UTC by slr42

2019-12-12 15:26 UTC, Smolevich commented on .phpunit.result.cache
> +C:37:"PHPUnit\Runner\DefaultTestResultCache":3256:{a:2:{s:7:"defects";a:1:{s:102:"Lamoda\IsmpClient\Tests\Impl\Serializer\SymfonySerializerAdapterTest::testDeserialize with data set #1";i:4;}s:5:"tim
Add file to .gitignore

2019-12-13 09:07 UTC, slr42 commented on .phpunit.result.cache
> +C:37:"PHPUnit\Runner\DefaultTestResultCache":3256:{a:2:{s:7:"defects";a:1:{s:102:"Lamoda\IsmpClient\Tests\Impl\Serializer\SymfonySerializerAdapterTest::testDeserialize with data set #1";i:4;}s:5:"tim
done

2019-12-13 09:34 UTC, slr42 commented on src/V3/Dto/FacadeDocListV2Query.php
> +     * @var string|null
PhpDocExtractor requires types to be annotated properly to work

2019-12-13 11:29 UTC, omnilight requested changes

2019-12-13 11:29 UTC, omnilight commented on tests/Impl/Serializer/FacadeDocBodyResponseBodyDenormalizerTest.php
> +        $this->inner = $this->getMockBuilder(DenormalizerInterface::class)
Давай так не делать - просто вызывай `createMock`, метод `setMethods` - deprecated

2019-12-13 11:29 UTC, omnilight commented on tests/V3/IsmpApiTest.php
> +    private const IDENTITY = 'eb852349-647f-468f-bb90-d26a4d975a88';
Спасибо, я не заметил

2019-12-13 11:29 UTC, omnilight commented on tests/Impl/Serializer/FacadeDocBodyResponseBodyDenormalizerTest.php
> +        $this->inner = $this->getMockBuilder(DenormalizerInterface::class)
Надо сделать тестовый объект, реализующий оба интерфейса. Это же кстати даст возможность протестировать передачу неверного сериалайзера

2019-12-13 11:56 UTC, Smolevich commented on .phpunit.result.cache
> +C:37:"PHPUnit\Runner\DefaultTestResultCache":3256:{a:2:{s:7:"defects";a:1:{s:102:"Lamoda\IsmpClient\Tests\Impl\Serializer\SymfonySerializerAdapterTest::testDeserialize with data set #1";i:4;}s:5:"tim
Delete this file from repo please

2019-12-13 12:23 UTC, slr42 commented on tests/Impl/Serializer/FacadeDocBodyResponseBodyDenormalizerTest.php
> +        $this->inner = $this->getMockBuilder(DenormalizerInterface::class)
ага, сделал. тест на невалидный сериалайзер добавил.

2019-12-13 12:40 UTC, slr42 commented on .phpunit.result.cache
> +C:37:"PHPUnit\Runner\DefaultTestResultCache":3256:{a:2:{s:7:"defects";a:1:{s:102:"Lamoda\IsmpClient\Tests\Impl\Serializer\SymfonySerializerAdapterTest::testDeserialize with data set #1";i:4;}s:5:"tim
done

2019-12-13 12:52 UTC, merged